### ISSUE TITLE
add link to contribute to affirmation generator to site

### ISSUE THREAD

**Issue by M0nica** [M0nica/affirmation_generator#28]
add the following text to the site: 
"Want to add a new affirmation?"
and a button with the text "Contribute"
 and the contribute button should link to this repository.

**Comment by ribaishtiaq** [comment]
![](https://res.cloudinary.com/areeba/image/upload/v1569931317/masPDoclRsgL4G.png)

**Comment by M0nica** [comment]
This was resolved in this PR https://github.com/M0nica/affirmation_generator/pull/45
