### ISSUE TITLE
Add instructions for contribution affirmations

### ISSUE THREAD

**Issue by M0nica** [M0nica/affirmation_generator#5]
Add instructions for contributing affirmations to the site via code changes. 

There are currently instructions in the README.

**Comment by M-ZubairAhmed** [comment]
Do you want the instructions to be displayed on website? If yes, do you have any particular design in mind

**Comment by tanyapowell** [comment]
Hey @M0nica, just ignore all the identical commits. I'm trying to figure out how to open 2 PRs from a forked repository 😄
