### ISSUE TITLE
top of homepage cut off

### ISSUE THREAD

**Issue by M0nica** [M0nica/affirmation_generator#56]
<img width="1165" alt="Screen Shot 2019-10-05 at 10 28 23 PM" src="https://user-images.githubusercontent.com/6998954/66263359-76d5be80-e7bf-11e9-8f42-d3fa1c319652.png">
'
Currently the "Affirmation Generator" h1 gets cut off on desktop screens. It should appear for all screen sizes. 

below is a screenshot of the text appearing on smaller screen

<img width="324" alt="Screen Shot 2019-10-05 at 10 29 13 PM" src="https://user-images.githubusercontent.com/6998954/66263366-940a8d00-e7bf-11e9-9b0d-9e010f96fae0.png">

**Comment by mikalai-sokarau** [comment]
Hello! I can check if this is still relevant :)

**Comment by M0nica** [comment]
@mikalai-sokarau this is still relevant and it would be great if you could look into this.

**Comment by Babadzhanov** [comment]
I will be happy to fix this.
