### ISSUE TITLE
generate image for twitter sharing 

### ISSUE THREAD

**Issue by M0nica** [M0nica/affirmation_generator#57]
Similar to how dev.to generates article preview images for social media -- should create a way to generate quote images for social media to be used in the share to twitter feature ![preview](https://user-images.githubusercontent.com/6998954/66263396-4a6e7200-e7c0-11e9-8b82-d923e942c35d.png)

**Comment by nsantos16** [comment]
Let me take this issue 💪

**Comment by M0nica** [comment]
We now have site-wide twitter image but it would be nice to be able to generate ones for each quote. I'll look into adding new routes to accomplish this.
